AllCops:
  TargetRubyVersion: 2.4
Style/RaiseArgs:
  EnforcedStyle: compact
Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space
Layout/MultilineOperationIndentation:
  EnforcedStyle: indented
Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented_relative_to_receiver
Metrics/LineLength:
  Max: 120
Metrics/BlockLength:
  Enabled: false
Metrics/MethodLength:
  Exclude:
    - 'spec/features/*_spec.rb'
Metrics/AbcSize:
  Exclude:
    - 'spec/features/*_spec.rb'
