version: '3.6'

services:
  devproxy:
    image: nginx
    ports:
      - 443:443
      - 2999:2999
    networks:
      default:
        aliases:
          {devproxy_aliases}
      external:
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
  mockserver:
    image: jamesdbloom/mockserver
    ports:
      - 1090:1080
    networks:
      default:
      external:
  sidekiq:
    image: eu.gcr.io/active-gasket-113610/argu:${RAILS_ENV:-staging}
    env_file:
      - ${ENV_FILE:-./.env}
    command: bundle exec sidekiq
    volumes:
      - ./devproxyCA/cacert.pem:/etc/ssl/certs/cacert.pem
  vote_compare_sidekiq:
    image: eu.gcr.io/active-gasket-113610/vote_compare_service:${RAILS_ENV:-staging}
    env_file:
      - ${ENV_FILE:-./.env}
    volumes:
      - ./devproxyCA/cacert.pem:/etc/ssl/certs/cacert.pem
    command: bundle exec sidekiq -e staging
  vote_compare_subscriber:
    image: eu.gcr.io/active-gasket-113610/vote_compare_service:${RAILS_ENV:-staging}
    env_file:
      - ${ENV_FILE:-./.env}
    volumes:
      - ./devproxyCA/cacert.pem:/etc/ssl/certs/cacert.pem
    command: bundle exec rake broadcast:subscribe
    depends_on:
      - rabbitmq
    restart: on-failure
  email_subscriber:
    image: eu.gcr.io/active-gasket-113610/email_service:${RAILS_ENV:-staging}
    env_file:
      - ${ENV_FILE:-./.env}
    volumes:
      - ./devproxyCA/cacert.pem:/etc/ssl/certs/cacert.pem
    command: bundle exec rake broadcast:subscribe
    depends_on:
      - rabbitmq
    restart: on-failure
  email_sidekiq:
    image: eu.gcr.io/active-gasket-113610/email_service:${RAILS_ENV:-staging}
    env_file:
      - ${ENV_FILE:-./.env}
    volumes:
      - ./devproxyCA/cacert.pem:/etc/ssl/certs/cacert.pem
    command: bundle exec sidekiq -e staging
  deku_sidekiq:
    image: eu.gcr.io/active-gasket-113610/deku:${RAILS_ENV:-staging}
    env_file:
      - ${ENV_FILE:-./.env}
    volumes:
      - ./devproxyCA/cacert.pem:/etc/ssl/certs/cacert.pem
    command: bundle exec sidekiq -e staging
  postgres:
    image: postgres:9.5.5
    env_file:
      - ${ENV_FILE:-./.env}
    networks:
      default:
      external:
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
  redis:
    image: redis:3.2.4
    ports:
      - 6379:6379
    networks:
      default:
      external:
  mailcatcher:
    image: schickling/mailcatcher
    networks:
      default:
      external:
    ports:
      - 1080:1080
  rabbitmq:
    image: healthcheck/rabbitmq
    ports:
      - 15672:15672
      - 5672:5672
    networks:
      default:
      external:
{webservices}
networks:
  default:
    internal: false
    ipam:
      config:
       - subnet: 172.99.0.0/16
  external:
volumes:
  pgdata:
