version: '3.6'

services:{testrunner}
  devproxy:
    build:
      context: .
      dockerfile: dockerfiles/nginx.Dockerfile
    ports:
      - 443:443
      - 80:80
      - 2999:2999
    extra_hosts:
      - host.docker.internal:${HOST_IP:-host-gateway}
    networks:
      default:
        aliases:
          - app.argu.localtest
          - argu.localtest
          - demogemeente.localdev
          - denkmee.drechtstedenenergie.localdev
          - veiligheidsinterventies.localdev
          - maatregelenwiki.localdev
          {devproxy_aliases}
      external:
  postgres:
    image: mdillon/postgis:9.5
    env_file:
      - ${ENV_FILE:-./.env}
    networks:
      default:
      external:
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
  redis:
    image: redis:6
    ports:
      - 6379:6379
    networks:
      default:
      external:
    volumes:
      - redisdata:/data
  elastic:
    image: elasticsearch:6.7.2
    env_file:
      - ${ENV_FILE:-./.env}
    environment:
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - "discovery.type=single-node"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    networks:
      default:
      external:
    ports:
      - 9200:9200
      - 9300:9300
  mailcatcher:
    command: ["mailcatcher", "--foreground", "--ip=0.0.0.0", "--smtp-port=1025", "--http-port=1080"]
    image: tophfr/mailcatcher:0.6.5_3
    ports:
      - 1080:1080
      - 1025:1025
  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    extra_hosts:
      - host.docker.internal:${HOST_IP:-host-gateway}
    networks:
      default:
        aliases:
          - prometheus
      external:
        aliases:
          - prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - promdata:/prometheus
  grafana:
    image: grafana/grafana
    environment:
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource,redis-datasource
    ports:
      - 8888:3000
    networks:
      default:
      external:
    volumes:
      - grafanadata:/var/lib/grafana
      - ./grafana/:/etc/grafana/provisioning/
{webservices}
networks:
  default:
    internal: false
    ipam:
      config:
       - subnet: 172.99.0.0/16
  external:
volumes:
  certdata:
  pgdata:
  redisdata:
  promdata:
  grafanadata:
