version: '3.6'

services:
  devproxy:
    image: nginx
    ports:
      - 443:443
      - 2999:2999
    networks:
      default:
#        aliases:
#          - argu.svc.cluster.local
      external:
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
  mockserver:
    image: jamesdbloom/mockserver
    ports:
      - 1090:1080
    networks:
      default:
      external:
  frontend:
    image: eu.gcr.io/active-gasket-113610/aod_demo:${RAILS_ENV:-staging}
    env_file:
      - ${ENV_FILE:-./.env}
    environment:
      - REDIS_ADDRESS=redis://redis:6379
    command: node --use-openssl-ca ./dist/private/server.js
    volumes:
      - ./devproxyCA/cacert.pem:/etc/ssl/certs/cacert.pem
  argu:
    image: eu.gcr.io/active-gasket-113610/argu:${RAILS_ENV:-staging}
    env_file:
      - ${ENV_FILE:-./.env}
    volumes:
      - ./devproxyCA/cacert.pem:/etc/ssl/certs/cacert.pem
    command: bundle exec unicorn -l 0.0.0.0 -p 2999 -c /usr/src/app/config/unicorn.rb
    expose:
      - 2999
    networks:
      default:
        aliases:
          - argu.svc.cluster.local
  sidekiq:
    image: eu.gcr.io/active-gasket-113610/argu:${RAILS_ENV:-staging}
    env_file:
      - ${ENV_FILE:-./.env}
    command: bundle exec sidekiq
    volumes:
      - ./devproxyCA/cacert.pem:/etc/ssl/certs/cacert.pem
  token_service:
    image: eu.gcr.io/active-gasket-113610/token_service:${RAILS_ENV:-staging}
    env_file:
      - ${ENV_FILE:-./.env}
    volumes:
      - ./devproxyCA/cacert.pem:/etc/ssl/certs/cacert.pem
    command: ./bin/rails server -b 0.0.0.0 -p 2999
    expose:
      - 2999
    networks:
      default:
        aliases:
          - token.svc.cluster.local
  vote_compare_service:
    image: eu.gcr.io/active-gasket-113610/vote_compare_service:${RAILS_ENV:-staging}
    env_file:
      - ${ENV_FILE:-./.env}
    volumes:
      - ./devproxyCA/cacert.pem:/etc/ssl/certs/cacert.pem
    command: ./bin/rails server -b 0.0.0.0 -p 2999
    expose:
      - 2999
    networks:
      default:
        aliases:
          - vote_compare.svc.cluster.local
  vote_compare_service_sidekiq:
    image: eu.gcr.io/active-gasket-113610/vote_compare_service:${RAILS_ENV:-staging}
    env_file:
      - ${ENV_FILE:-./.env}
    volumes:
      - ./devproxyCA/cacert.pem:/etc/ssl/certs/cacert.pem
    command: bundle exec sidekiq -e staging
  vote_compare_service_subscriber:
    image: eu.gcr.io/active-gasket-113610/vote_compare_service:${RAILS_ENV:-staging}
    env_file:
      - ${ENV_FILE:-./.env}
    volumes:
      - ./devproxyCA/cacert.pem:/etc/ssl/certs/cacert.pem
    command: bundle exec rake broadcast:subscribe
    depends_on:
      - rabbitmq
    restart: on-failure
  email_service:
    image: eu.gcr.io/active-gasket-113610/email_service:${RAILS_ENV:-staging}
    env_file:
      - ${ENV_FILE:-./.env}
    volumes:
      - ./devproxyCA/cacert.pem:/etc/ssl/certs/cacert.pem
    command: ./bin/rails server -b 0.0.0.0 -p 2999
    expose:
      - 2999
    networks:
      default:
        aliases:
          - email.svc.cluster.local
  email_service_subscriber:
    image: eu.gcr.io/active-gasket-113610/email_service:${RAILS_ENV:-staging}
    env_file:
      - ${ENV_FILE:-./.env}
    volumes:
      - ./devproxyCA/cacert.pem:/etc/ssl/certs/cacert.pem
    command: bundle exec rake broadcast:subscribe
    depends_on:
      - rabbitmq
    restart: on-failure
  email_service_sidekiq:
    image: eu.gcr.io/active-gasket-113610/email_service:${RAILS_ENV:-staging}
    env_file:
      - ${ENV_FILE:-./.env}
    volumes:
      - ./devproxyCA/cacert.pem:/etc/ssl/certs/cacert.pem
    command: bundle exec sidekiq -e staging
  deku_service:
    image: eu.gcr.io/active-gasket-113610/deku:${RAILS_ENV:-staging}
    env_file:
      - ${ENV_FILE:-./.env}
    volumes:
      - ./devproxyCA/cacert.pem:/etc/ssl/certs/cacert.pem
    command: ./bin/rails server -b 0.0.0.0 -p 2999
    expose:
      - 2999
    networks:
      default:
        aliases:
          - deku.svc.cluster.local
  deku_service_sidekiq:
    image: eu.gcr.io/active-gasket-113610/deku:${RAILS_ENV:-staging}
    env_file:
      - ${ENV_FILE:-./.env}
    volumes:
      - ./devproxyCA/cacert.pem:/etc/ssl/certs/cacert.pem
    command: bundle exec sidekiq -e staging
  postgres:
    image: postgres:9.5.5
    env_file:
      - ${ENV_FILE:-./.env}
    networks:
      default:
      external:
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
  redis:
    image: redis:3.2.4
    ports:
      - 6379:6379
    networks:
      default:
      external:
  mailcatcher:
    image: schickling/mailcatcher
    networks:
      default:
      external:
    ports:
      - 1080:1080
  rabbitmq:
    image: healthcheck/rabbitmq
    ports:
      - 15672:15672
      - 5672:5672
    networks:
      default:
      external:
networks:
  default:
    internal: ${RESTRICT_EXTERNAL_NETWORK:-true}
    ipam:
      config:
       - subnet: 172.99.0.0/16
  external:
volumes:
  pgdata:
