# frozen_string_literal: true

source 'https://rubygems.org/'
ruby '~> 3'

gem 'activesupport'
gem 'capybara'
gem 'capybara-screenshot'
gem 'docker-api'
gem 'dotenv'
gem 'faraday'
gem 'http-cookie'
gem 'httparty'
gem 'linked_rails', git: 'https://github.com/ontola/linked_rails', branch: :empathy
gem 'mailcatcher-api'
gem 'oj'
gem 'rake'
gem 'rdf'
gem 'rdf-vocab'
gem 'redis'
gem 'rexml'
gem 'rspec'
gem 'rspec-instafail'
gem 'rspec-retry'
gem 'rspec-wait'
gem 'rspec_junit_formatter'
gem 'rubocop'
gem 'selenium-webdriver'
gem 'webdrivers'
