# frozen_string_literal: true

source 'https://rubygems.org/'

gem 'activesupport'
gem 'capybara'
gem 'capybara-screenshot'
gem 'docker-api'
gem 'dotenv'
gem 'faraday'
gem 'http-cookie'
gem 'httparty'
gem 'oj'
gem 'mailcatcher-api'
gem 'rake'
gem 'rdf'
gem 'rspec'
gem 'rspec-instafail'
gem 'rspec_junit_formatter'
gem 'rspec-wait'
gem 'rubocop'
gem 'selenium-webdriver'
gem 'webdrivers'
