# frozen_string_literal: true

source 'https://rubygems.org/'
ruby '3.0.2'

gem 'activesupport'
gem 'capybara'
gem 'capybara-playwright-driver'
gem 'docker-api'
gem 'dotenv'
gem 'emp-json'
gem 'faraday'
gem 'faraday-multipart'
gem 'http-cookie'
gem 'httparty'
gem 'mailcatcher-api'
gem 'oj'
gem 'rake'
gem 'rdf'
gem 'rdf-vocab'
gem 'redis'
gem 'rspec'
gem 'rspec-instafail'
gem 'rspec_junit_formatter'
gem 'rspec-retry'
gem 'rspec-wait'
gem 'rubocop'
